name: Microsoft C++ Code Analysis

on: [ workflow_dispatch ]

permissions:
  contents: read

jobs:
  analyze:
    env:
      build_dir: '${{ github.workspace }}/build'

    permissions:
      contents: read            # for actions/checkout to fetch code
      security-events: write    # for github/codeql-action/upload-sarif to upload SARIF results

    name: ${{ matrix.os }} - ${{ matrix.cmake_preset }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        build_type: [ debug ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # env:
        #   VCPKG_ROOT: "C:\\vcpkg"
        # with:
        #   cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        #   configurePreset: ${{ matrix.build_type }}
      
      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        # Provide a unique ID to access the sarif output path
        id: run-analysis
        with:
          cmakeBuildDirectory: ${{ env.build }}
          buildConfiguration: ${{ matrix.build_type }}
          # Ruleset file that will determine what checks will be run
          ruleset: NativeRecommendedRules.ruleset
          # Paths to ignore analysis of CMake targets and includes
          ignoredPaths: ${{ github.workspace }}/_deps;${{ github.workspace }}/tests

        # uses: microsoft/msvc-code-analysis-action@v0.1.1
        # # Provide a unique ID to access the sarif output path
        # id: run-analysis
        # with:
        #   cmakeBuildDirectory: ${{ env.CONFIG_DIR }}
        #   # Ruleset file that will determine what checks will be run
        #   ruleset: NativeRecommendedRules.ruleset

      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
        
      # Upload SARIF file as an Artifact to download and view
      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sarif-file
          path: ${{ steps.run-analysis.outputs.sarif }}


# name: Microsoft C++ Code Analysis

# on: [ workflow_dispatch ]

# permissions:
#   contents: read

# env:
#   build_dir: '${{ github.workspace }}/build'
#   build_type: 'Debug'

# jobs:
#   analyze:
#     name: Analyze
#     runs-on: windows-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Configure CMake
#         run: cmake -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.build_type }}

#       - name: Run MSVC Code Analysis
#         uses: microsoft/msvc-code-analysis-action@v0.1.1
#         # Provide a unique ID to access the sarif output path
#         id: run-analysis
#         with:
#           cmakeBuildDirectory: ${{ env.build }}
#           buildConfiguration: ${{ env.config }}
#           # Ruleset file that will determine what checks will be run
#           ruleset: NativeRecommendedRules.ruleset
#           # Paths to ignore analysis of CMake targets and includes
#           ignoredPaths: ${{ github.workspace }}/_deps;${{ github.workspace }}/tests

#       # Upload SARIF file to GitHub Code Scanning Alerts
#       - name: Upload SARIF to GitHub
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: ${{ steps.run-analysis.outputs.sarif }}

#       # Upload SARIF file as an Artifact to download and view
#       - name: Upload SARIF as an Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: sarif-file
#           path: ${{ steps.run-analysis.outputs.sarif }}




