name: Test Ninja

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          #- { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          #- { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++" }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # - name: Setup Ninja
      #   uses: ashutoshvarma/setup-ninja@master
      #   with:
      #     # ninja version to download. Default: 1.10.0
      #     version: 1.10.0

      - name: Config
        run: >-
          cmake -G Ninja -B build
          -D CMAKE_CXX_COMPILER="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/HostX64/x64/cl.exe"
          -D CMAKE_RC_COMPILER="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/HostX64/x64/cl.exe"

      - name: Build
        run: cmake --build . --config Release

      # - name: Build with CMake
      #   uses: ashutoshvarma/action-cmake-build@master
      #   with:
      #     build-dir: ${{ runner.workspace }}/build
      #     cc: ${{ matrix.config.cc }}
      #     cxx: ${{ matrix.config.cxx }}
      #     configure-options: -G Ninja
      #     build-type: Release